In [1]:
import numpy as np

In [5]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10]

In [9]:
a = np.array(list)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
b = np.random.randn(3, 4)
b

array([[-0.78147366,  0.52179917, -0.78754549,  0.75478007],
       [ 0.39072314,  0.56186989, -1.84937898, -0.75861416],
       [-1.25515149, -0.02182218,  0.42533083, -0.34818935]])

In [45]:
c = np.zeros((2, 3, 4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [57]:
# Element wise operations
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
c = np.array(a) + np.array(b)
c

array([ 7,  9, 11, 13, 15])

In [61]:
d = np.array(a) - np.array(b)
d

array([-5, -5, -5, -5, -5])

In [65]:
e = np.array(a) * np.array(b)
e

array([ 6, 14, 24, 36, 50])

In [69]:
f = np.array(a) / np.array(b)
f

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [73]:
# Calculating mean, median, standard deviation
list = [1, 2, 3, 4, 5]
a = np.array(list)
mean = np.mean(a)
mean

3.0

In [77]:
median = np.median(a)
median

3.0

In [81]:
std = np.std(a)
std

1.4142135623730951

In [91]:
# Arranging 1d array in 2d array of shape (3, 4)
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
arr = np.array(list)
array_2D = arr.reshape(3, 4)
array_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
# Array Indexing and Slicing
# abstracting first row and last column of 2D array
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2D = np.array(arr)
# first row 
arr_2D[0]

array([1, 2, 3])

In [115]:
# last column
last_column = arr_2D[:, -1]
print(last_column)

[3 6 9]


In [123]:
# Reverse the order of element in 1D array
list = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(list)
rev = np.flip(arr)
rev

array([8, 7, 6, 5, 4, 3, 2, 1])

In [137]:
# Selecting element from 2D array that specify certain threshold
list = [[1, 2, 3, 4], [5, 6, 7, 8]]
Two = np.array(list)
element_gt_2 = Two[Two > 5]
print(element_gt_2)

[6 7 8]


In [141]:
# Array Broadcasting
# Adding scalar value to each element
two = [[1, 2, 3], [4, 5, 6]]
arr_2D = np.array(two)
scalar_value = arr_2D + 2
scalar_value

array([[3, 4, 5],
       [6, 7, 8]])

In [149]:
# Multiplying 1D array with 2D array using broadcasting rule
a = [1, 2, 3]
one = np.array(a)
b = [[4, 5, 6], [7, 8, 9], [10, 11, 12]]
two = np.array(b)
broadcasted_mul = one * two
broadcasted_mul

array([[ 4, 10, 18],
       [ 7, 16, 27],
       [10, 22, 36]])

In [153]:
# Linear Algebra
# dot product of two 1d array
one = np.array([1, 2, 3, 4, 5])
two = np.array([6, 7, 8, 9, 10])
dot_product = np.dot(one, two)
dot_product

130

In [159]:
# Matrix Multipication of 2D array
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
dot_mul_2D = np.dot(a, b)
dot_mul_2D

array([[19, 22],
       [43, 50]])

In [177]:
# Inverse and Determinant of a square matrix
a = np.array([[4, 7], [2, 6]])
# calculate determinant
determinant = np.linalg.det(a)
('The determinant of square matrix is:', determinant)

('The determinant of square matrix is:', 10.000000000000002)

In [169]:
if determinant !=0 :
    inverse_matrix = np.linalg.inv(a)
    print(inverse_matrix)
else:
    print('Matrix is singular and doesnot have an inverse')

[[ 0.6 -0.7]
 [-0.2  0.4]]
